@extends('layouts.app')
@section('title','Centro de conciliación · ARIONS FINANCE')
@section('content')
<div class="page-head"><div><span class="eyebrow">Reconciliation workspace</span><h1>Centro de conciliación</h1><p>Revisa movimientos pendientes y resuelve únicamente las excepciones.</p></div></div>
<div class="metrics"><article><span>Pendientes visibles</span><strong>{{$transactions->total()}}</strong><small>Según filtros actuales</small></article><article><span>Objetivo</span><strong>1:1</strong><small>Matching activo en este incremento</small></article><article><span>Scoring</span><strong>0–100%</strong><small>Monto, moneda, fecha, folio y RUT</small></article><article><span>Control</span><strong>Manual</strong><small>La IA aún no modifica datos</small></article><form method="post" action="{{route('reconciliation.auto-run')}}">@csrf<button class="primary">Ejecutar conciliación automática</button></form></div>
<div class="panel"><div class="panel-head"><h2>Movimientos por resolver</h2><form method="get"><input name="q" value="{{request('q')}}" placeholder="Buscar descripción o referencia"><button class="ghost">Buscar</button></form></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Cuenta</th><th>Movimiento</th><th>Estado</th><th class="right">Monto</th><th></th></tr></thead><tbody>
@forelse($transactions as $tx)<tr><td>{{$tx->booking_date?->format('d/m/Y')}}</td><td>{{$tx->bankAccount?->name ?? '—'}}<small>{{$tx->currency}}</small></td><td>{{$tx->description_normalized ?: $tx->description_raw}}<small>{{$tx->reference ?: 'Sin referencia'}}</small></td><td><span class="badge">{{$tx->status->value ?? $tx->status}}</span></td><td class="right money">$ {{number_format(abs((float)$tx->amount),0,',','.')}}</td><td class="right"><a class="button compact" href="{{route('reconciliation.show',$tx)}}">Revisar</a></td></tr>@empty<tr><td colspan="6" class="empty">No hay movimientos pendientes de conciliación.</td></tr>@endforelse
</tbody></table></div><div class="pager">{{$transactions->links()}}</div></div>
@endsection
