@extends('layouts.app')
@section('title','Revisar conciliación · ARIONS FINANCE')
@section('content')
<div class="page-head"><div><span class="eyebrow">Revisión humana</span><h1>Conciliar movimiento</h1><p>Compara la evidencia bancaria con los documentos candidatos antes de aprobar.</p></div><a class="ghost" href="{{route('reconciliation.index')}}">← Volver</a></div>
<div class="reconcile-layout"><section class="panel"><div class="panel-head"><h2>Movimiento bancario</h2><span class="badge">{{$transaction->status->value ?? $transaction->status}}</span></div><div class="detail-grid"><div><span>Fecha</span><strong>{{$transaction->booking_date?->format('d/m/Y')}}</strong></div><div><span>Monto</span><strong>$ {{number_format(abs((float)$transaction->amount),0,',','.')}} {{$transaction->currency}}</strong></div><div><span>Cuenta</span><strong>{{$transaction->bankAccount?->name ?? '—'}}</strong></div><div><span>RUT contraparte</span><strong>{{$transaction->counterparty_tax_id ?: 'No informado'}}</strong></div><div class="wide"><span>Descripción original</span><strong>{{$transaction->description_raw}}</strong></div><div class="wide"><span>Referencia</span><strong>{{$transaction->reference ?: 'Sin referencia'}}</strong></div></div><div class="danger-zone"><form method="post" action="{{route('reconciliation.reject',$transaction)}}">@csrf<button class="ghost">Marcar como ignorado</button></form></div></section>
<section class="panel"><div class="panel-head"><div><span class="eyebrow">Candidatos</span><h2>Documentos sugeridos</h2></div><span>{{count($candidates)}} encontrados</span></div>
@forelse($candidates as $candidate) @php($doc=$candidate['document']) @php($score=$candidate['score'])
<div class="candidate"><div class="candidate-top"><div><strong>{{$doc->document_type}} · {{$doc->folio}}</strong><small>{{$doc->counterparty?->name ?? 'Contraparte sin nombre'}} · vence {{$doc->due_date?->format('d/m/Y') ?? 'sin vencimiento'}}</small></div><div class="score {{ $score->score>=80?'score-good':($score->score>=60?'score-warn':'') }}">{{number_format($score->score,1)}}%</div></div><div class="candidate-money">Saldo documento: <strong>$ {{number_format((float)$doc->open_amount,0,',','.')}} {{$doc->currency}}</strong></div><div class="reason-list">@forelse($score->reasons as $reason)<span>✓ {{$reason}}</span>@empty<span>Sin evidencia fuerte adicional</span>@endforelse</div><form method="post" action="{{route('reconciliation.approve',$transaction)}}">@csrf<input type="hidden" name="financial_document_id" value="{{$doc->id}}"><input type="hidden" name="score" value="{{$score->score}}"><button class="primary" onclick="return confirm('¿Confirmas aplicar este movimiento al documento {{$doc->folio}}?')">Conciliar con este documento</button></form></div>
@empty<div class="empty">No encontramos candidatos dentro del rango inicial. El movimiento debe permanecer pendiente para una búsqueda ampliada o clasificación asistida.</div>@endforelse
</section></div>
@endsection
