<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('banks',function(Blueprint $t){$t->ulid('id')->primary();$t->string('code',40)->unique();$t->string('name');$t->char('country',2)->default('CL');$t->string('status',24)->default('active');$t->timestamps();});
Schema::create('bank_accounts',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('organization_id')->constrained()->cascadeOnDelete();$t->foreignUlid('bank_id')->constrained()->restrictOnDelete();$t->string('external_id')->nullable();$t->string('name')->nullable();$t->string('account_type',40);$t->char('currency',3)->default('CLP');$t->string('masked_number',64)->nullable();$t->string('status',24)->default('active');$t->timestamps();$t->unique(['organization_id','bank_id','external_id']);$t->index(['organization_id','status']);});
Schema::create('bank_connections',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('organization_id')->constrained()->cascadeOnDelete();$t->foreignUlid('bank_id')->constrained()->restrictOnDelete();$t->string('provider');$t->text('encrypted_credentials')->nullable();$t->timestampTz('consent_expires_at')->nullable();$t->string('status',24)->default('inactive');$t->timestamps();$t->index(['organization_id','bank_id']);});
Schema::create('bank_imports',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('organization_id')->constrained()->cascadeOnDelete();$t->foreignUlid('bank_account_id')->constrained()->cascadeOnDelete();$t->string('source',32);$t->char('file_hash',64)->nullable();$t->string('status',24)->default('pending');$t->unsignedBigInteger('rows_total')->default(0);$t->unsignedBigInteger('rows_imported')->default(0);$t->unsignedBigInteger('rows_duplicate')->default(0);$t->unsignedBigInteger('rows_failed')->default(0);$t->jsonb('metadata')->nullable();$t->timestamps();$t->unique(['organization_id','bank_account_id','file_hash']);});
Schema::create('bank_statements',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('organization_id')->constrained()->cascadeOnDelete();$t->foreignUlid('bank_account_id')->constrained()->cascadeOnDelete();$t->date('period_from');$t->date('period_to');$t->decimal('opening_balance',20,4)->nullable();$t->decimal('closing_balance',20,4)->nullable();$t->char('currency',3)->default('CLP');$t->timestamps();$t->index(['organization_id','bank_account_id','period_from','period_to']);});
Schema::create('bank_transactions',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('organization_id')->constrained()->cascadeOnDelete();$t->foreignUlid('bank_account_id')->constrained()->cascadeOnDelete();$t->foreignUlid('statement_id')->nullable()->constrained('bank_statements')->nullOnDelete();$t->string('external_id')->nullable();$t->date('booking_date');$t->date('value_date')->nullable();$t->decimal('amount',20,4);$t->char('currency',3)->default('CLP');$t->string('direction',12);$t->text('description_raw');$t->text('description_normalized')->nullable();$t->string('reference')->nullable();$t->string('operation_number')->nullable();$t->string('counterparty_tax_id',32)->nullable();$t->string('counterparty_name')->nullable();$t->decimal('balance_after',20,4)->nullable();$t->char('fingerprint',64);$t->string('status',32)->default('imported');$t->timestamps();$t->unique(['organization_id','bank_account_id','fingerprint']);$t->index(['organization_id','bank_account_id','booking_date']);$t->index(['organization_id','status','booking_date']);});
Schema::create('transaction_raw_data',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('bank_transaction_id')->unique()->constrained()->cascadeOnDelete();$t->jsonb('payload');$t->timestamps();});
Schema::create('transaction_duplicates',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('transaction_id')->constrained('bank_transactions')->cascadeOnDelete();$t->foreignUlid('duplicate_of_id')->constrained('bank_transactions')->cascadeOnDelete();$t->string('reason');$t->timestamps();$t->unique(['transaction_id','duplicate_of_id']);});
} public function down(): void { foreach(['transaction_duplicates','transaction_raw_data','bank_transactions','bank_statements','bank_imports','bank_connections','bank_accounts','banks'] as $x) Schema::dropIfExists($x); } };
